# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'LCEBarnSwallow' do
	
	pod 'MJRefresh'
    pod 'SQLite.swift'
    pod 'IQKeyboardManagerSwift'
    pod 'Moya'
    pod 'SnapKit'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'ObjectMapper'
    pod 'SVProgressHUD'
    pod 'Kingfisher'

end

target 'LCEBarnSwallowTests' do
    inherit! :search_paths
    # Pods for testing
end

